# Generated by Django 5.0.6 on 2024-07-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
    ]
