# Generated by Django 5.0.6 on 2024-07-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
