# Generated by Django 5.0.6 on 2024-07-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='totalprice',
        ),
    ]
