# Generated by Django 5.0.6 on 2024-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cartitem_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
