# Generated by Django 5.0.6 on 2024-07-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_cartitem_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
